
package lab3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AuthException", targetNamespace = "http://lab3/")
public class AuthException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceExceptionFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AuthException(String message, ServiceExceptionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AuthException(String message, ServiceExceptionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: lab3.ServiceExceptionFault
     */
    public ServiceExceptionFault getFaultInfo() {
        return faultInfo;
    }

}
