
package lab3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BaseServiceException", targetNamespace = "http://lab3/")
public class BaseServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BaseServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BaseServiceException_Exception(String message, BaseServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BaseServiceException_Exception(String message, BaseServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: lab3.BaseServiceException
     */
    public BaseServiceException getFaultInfo() {
        return faultInfo;
    }

}
