
package lab2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LaptopWebService", targetNamespace = "http://lab2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LaptopWebService {


    /**
     * 
     * @param videoCard
     * @param name
     * @param cpu
     * @param hdd
     * @param ram
     * @return
     *     returns java.util.List<lab2.Laptop>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLaptopsByFilter", targetNamespace = "http://lab2/", className = "lab2.GetLaptopsByFilter")
    @ResponseWrapper(localName = "getLaptopsByFilterResponse", targetNamespace = "http://lab2/", className = "lab2.GetLaptopsByFilterResponse")
    @Action(input = "http://lab2/LaptopWebService/getLaptopsByFilterRequest", output = "http://lab2/LaptopWebService/getLaptopsByFilterResponse")
    public List<Laptop> getLaptopsByFilter(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "CPU", targetNamespace = "")
        String cpu,
        @WebParam(name = "RAM", targetNamespace = "")
        String ram,
        @WebParam(name = "video_card", targetNamespace = "")
        String videoCard,
        @WebParam(name = "HDD", targetNamespace = "")
        String hdd);

    /**
     * 
     * @param laptop
     * @return
     *     returns lab2.ResultStatusOperation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertLaptop", targetNamespace = "http://lab2/", className = "lab2.InsertLaptop")
    @ResponseWrapper(localName = "insertLaptopResponse", targetNamespace = "http://lab2/", className = "lab2.InsertLaptopResponse")
    @Action(input = "http://lab2/LaptopWebService/insertLaptopRequest", output = "http://lab2/LaptopWebService/insertLaptopResponse")
    public ResultStatusOperation insertLaptop(
        @WebParam(name = "laptop", targetNamespace = "")
        Laptop laptop);

    /**
     * 
     * @return
     *     returns lab2.ResultStatusOperation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAllLaptops", targetNamespace = "http://lab2/", className = "lab2.DeleteAllLaptops")
    @ResponseWrapper(localName = "deleteAllLaptopsResponse", targetNamespace = "http://lab2/", className = "lab2.DeleteAllLaptopsResponse")
    @Action(input = "http://lab2/LaptopWebService/deleteAllLaptopsRequest", output = "http://lab2/LaptopWebService/deleteAllLaptopsResponse")
    public ResultStatusOperation deleteAllLaptops();

    /**
     * 
     * @return
     *     returns java.util.List<lab2.Laptop>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLaptops", targetNamespace = "http://lab2/", className = "lab2.GetLaptops")
    @ResponseWrapper(localName = "getLaptopsResponse", targetNamespace = "http://lab2/", className = "lab2.GetLaptopsResponse")
    @Action(input = "http://lab2/LaptopWebService/getLaptopsRequest", output = "http://lab2/LaptopWebService/getLaptopsResponse")
    public List<Laptop> getLaptops();

    /**
     * 
     * @param id
     * @return
     *     returns lab2.ResultStatusOperation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLaptop", targetNamespace = "http://lab2/", className = "lab2.DeleteLaptop")
    @ResponseWrapper(localName = "deleteLaptopResponse", targetNamespace = "http://lab2/", className = "lab2.DeleteLaptopResponse")
    @Action(input = "http://lab2/LaptopWebService/deleteLaptopRequest", output = "http://lab2/LaptopWebService/deleteLaptopResponse")
    public ResultStatusOperation deleteLaptop(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param laptop
     * @return
     *     returns lab2.ResultStatusOperation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLaptop", targetNamespace = "http://lab2/", className = "lab2.UpdateLaptop")
    @ResponseWrapper(localName = "updateLaptopResponse", targetNamespace = "http://lab2/", className = "lab2.UpdateLaptopResponse")
    @Action(input = "http://lab2/LaptopWebService/updateLaptopRequest", output = "http://lab2/LaptopWebService/updateLaptopResponse")
    public ResultStatusOperation updateLaptop(
        @WebParam(name = "laptop", targetNamespace = "")
        Laptop laptop);

}
