
package lab2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LaptopService", targetNamespace = "http://lab2/", wsdlLocation = "http://localhost:8080/LaptopService?wsdl")
public class LaptopService
    extends Service
{

    private final static URL LAPTOPSERVICE_WSDL_LOCATION;
    private final static WebServiceException LAPTOPSERVICE_EXCEPTION;
    private final static QName LAPTOPSERVICE_QNAME = new QName("http://lab2/", "LaptopService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LaptopService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LAPTOPSERVICE_WSDL_LOCATION = url;
        LAPTOPSERVICE_EXCEPTION = e;
    }

    public LaptopService() {
        super(__getWsdlLocation(), LAPTOPSERVICE_QNAME);
    }

    public LaptopService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LAPTOPSERVICE_QNAME, features);
    }

    public LaptopService(URL wsdlLocation) {
        super(wsdlLocation, LAPTOPSERVICE_QNAME);
    }

    public LaptopService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LAPTOPSERVICE_QNAME, features);
    }

    public LaptopService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LaptopService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LaptopWebService
     */
    @WebEndpoint(name = "LaptopWebServicePort")
    public LaptopWebService getLaptopWebServicePort() {
        return super.getPort(new QName("http://lab2/", "LaptopWebServicePort"), LaptopWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LaptopWebService
     */
    @WebEndpoint(name = "LaptopWebServicePort")
    public LaptopWebService getLaptopWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lab2/", "LaptopWebServicePort"), LaptopWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LAPTOPSERVICE_EXCEPTION!= null) {
            throw LAPTOPSERVICE_EXCEPTION;
        }
        return LAPTOPSERVICE_WSDL_LOCATION;
    }

}
